@startuml
class vigilancia.sistema.Vigilante {
- int codigo
- int edad
- String nombre
+ int getCodigo()
+ void setCodigo(int)
+ int getEdad()
+ void setEdad(int)
+ String getNombre()
+ void setNombre(String)
}


class vigilancia.sistema.Sucursal {
- EntidadBancaria entidad
- int codigo
- int cantidadEmpleados
- String domicilio
- ArrayList<Contrato> contratosVigentes
+ EntidadBancaria getEntidad()
- void setEntidad(EntidadBancaria)
+ String getDomicilio()
+ void setDomicilio(String)
+ int getCodigo()
+ void setCodigo(int)
+ int getCantidadEmpleados()
+ ArrayList<Contrato> getContratosVigentes()
+ void addContrato(Contrato)
+ ArrayList<Vigilante> getVigilantes()
}


class dv.torneo.Player {
- int number
- String name
- String position
- int goalCounter
+ int getNumber()
+ void setNumber(int)
+ String getName()
+ void setName(String)
+ String getPosition()
+ void setPosition(String)
+ int getGoalCounter()
+ void setGoalCounter(int)
}


class vigilancia.sistema.EntidadBancaria {
- int codigo
- String nombre
- String domicilio
- ArrayList<Sucursal> sucursales
+ int getCodigo()
+ void setCodigo(int)
+ String getNombre()
+ void setNombre(String)
+ String getDomicilio()
+ void setDomicilio(String)
+ ArrayList<Sucursal> getSucursales()
+ void addSucursal(Sucursal)
+ void addSucursal(int,String)
+ void removeSucursal(int)
+ void removeSucursal(Sucursal)
}


class Main {
+ {static} void main(String[])
}

class vigilancia.sistema.Contrato {
- boolean activo
- Date fechaContratacion
- Date fechaCierre
- boolean conArma
- Vigilante vigilante
+ boolean isActivo()
+ void setActivo(boolean)
+ Date getFechaContratacion()
+ void setFechaContratacion(Date)
+ Date getFechaCierre()
+ void setFechaCierre(Date)
+ boolean isConArma()
+ Vigilante getVigilante()
+ void setVigilante(Vigilante)
}


@enduml