@startuml
class vigilancia.sistema.EntidadBancaria {
- int codigo
- String nombre
- String domicilio
- ArrayList<Sucursal> sucursales
+ int getCodigo()
+ void setCodigo(int)
+ String getNombre()
+ void setNombre(String)
+ String getDomicilio()
+ void setDomicilio(String)
+ ArrayList<Sucursal> getSucursales()
+ void addSucursal(Sucursal)
+ void addSucursal(int,String)
+ void removeSucursal(int)
+ void removeSucursal(Sucursal)
}


class vigilancia.sistema.Sucursal {
- EntidadBancaria entidad
- int codigo
- int cantidadEmpleados
- String domicilio
+ EntidadBancaria getEntidad()
- void setEntidad(EntidadBancaria)
+ String getDomicilio()
+ void setDomicilio(String)
+ int getCodigo()
+ void setCodigo(int)
+ int getCantidadEmpleados()
}


class Main {
+ {static} void main(String[])
}

@enduml